# Generated by Django 3.2.2 on 2021-05-06 18:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FinalApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_since',
            field=models.DateField(default=datetime.datetime(2021, 5, 6, 14, 22, 40, 928939)),
        ),
        migrations.AlterField(
            model_name='order',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2022, 5, 6, 14, 22, 40, 929937)),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(default=datetime.datetime(2021, 5, 6, 14, 22, 40, 929937)),
        ),
    ]
